/**
 *
 * $Id$
 */
package Metawebdesign.metawebdesign.validation;

import Metawebdesign.metawebdesign.TypeAttributeForm;
import Metawebdesign.metawebdesign.TypeData;
import Metawebdesign.metawebdesign.TypeRol;

/**
 * A sample validator interface for {@link Metawebdesign.metawebdesign.Attributes}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AttributesValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateRol(TypeRol value);
	boolean validateValue(String value);
	boolean validatePrimaryKey(boolean value);
	boolean validateDataType(TypeData value);
	boolean validateInTheForm(TypeAttributeForm value);
}
