/**
 *
 * $Id$
 */
package Metawebdesign.metawebdesign.validation;

import Metawebdesign.metawebdesign.Group;
import Metawebdesign.metawebdesign.RelationView;
import Metawebdesign.metawebdesign.TypeRol;

/**
 * A sample validator interface for {@link Metawebdesign.metawebdesign.Views}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ViewsValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateRolView(TypeRol value);
	boolean validateGroupName(Group value);
	boolean validateHasRelationView(RelationView value);
	boolean validateFromRelation(RelationView value);
}
