/**
 */
package Modeluno.modeluno.provider;

import Modeluno.modeluno.util.ModelunoAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ModelunoItemProviderAdapterFactory extends ModelunoAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ModelunoItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.Map} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MapItemProvider mapItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.Map}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMapAdapter() {
		if (mapItemProvider == null) {
			mapItemProvider = new MapItemProvider(this);
		}

		return mapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.Class} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassItemProvider classItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.Class}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassAdapter() {
		if (classItemProvider == null) {
			classItemProvider = new ClassItemProvider(this);
		}

		return classItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.RelationClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationClassItemProvider relationClassItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.RelationClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationClassAdapter() {
		if (relationClassItemProvider == null) {
			relationClassItemProvider = new RelationClassItemProvider(this);
		}

		return relationClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.Attribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeItemProvider attributeItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.Attribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeAdapter() {
		if (attributeItemProvider == null) {
			attributeItemProvider = new AttributeItemProvider(this);
		}

		return attributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.RelationAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationAttributeItemProvider relationAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.RelationAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationAttributeAdapter() {
		if (relationAttributeItemProvider == null) {
			relationAttributeItemProvider = new RelationAttributeItemProvider(this);
		}

		return relationAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.Attribute_Not_Derived} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Attribute_Not_DerivedItemProvider attribute_Not_DerivedItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.Attribute_Not_Derived}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttribute_Not_DerivedAdapter() {
		if (attribute_Not_DerivedItemProvider == null) {
			attribute_Not_DerivedItemProvider = new Attribute_Not_DerivedItemProvider(this);
		}

		return attribute_Not_DerivedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.Attribute_Derived} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Attribute_DerivedItemProvider attribute_DerivedItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.Attribute_Derived}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttribute_DerivedAdapter() {
		if (attribute_DerivedItemProvider == null) {
			attribute_DerivedItemProvider = new Attribute_DerivedItemProvider(this);
		}

		return attribute_DerivedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.Service} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceItemProvider serviceItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.Service}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAdapter() {
		if (serviceItemProvider == null) {
			serviceItemProvider = new ServiceItemProvider(this);
		}

		return serviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.RelationService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationServiceItemProvider relationServiceItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.RelationService}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationServiceAdapter() {
		if (relationServiceItemProvider == null) {
			relationServiceItemProvider = new RelationServiceItemProvider(this);
		}

		return relationServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.Create} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateItemProvider createItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.Create}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateAdapter() {
		if (createItemProvider == null) {
			createItemProvider = new CreateItemProvider(this);
		}

		return createItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.Delete} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeleteItemProvider deleteItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.Delete}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeleteAdapter() {
		if (deleteItemProvider == null) {
			deleteItemProvider = new DeleteItemProvider(this);
		}

		return deleteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.UpdateObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UpdateObjectItemProvider updateObjectItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.UpdateObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUpdateObjectAdapter() {
		if (updateObjectItemProvider == null) {
			updateObjectItemProvider = new UpdateObjectItemProvider(this);
		}

		return updateObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.UpdateAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UpdateAttributeItemProvider updateAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.UpdateAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUpdateAttributeAdapter() {
		if (updateAttributeItemProvider == null) {
			updateAttributeItemProvider = new UpdateAttributeItemProvider(this);
		}

		return updateAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.ListView} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListViewItemProvider listViewItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.ListView}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListViewAdapter() {
		if (listViewItemProvider == null) {
			listViewItemProvider = new ListViewItemProvider(this);
		}

		return listViewItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.View} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewItemProvider viewItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.View}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewAdapter() {
		if (viewItemProvider == null) {
			viewItemProvider = new ViewItemProvider(this);
		}

		return viewItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.Admin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AdminItemProvider adminItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.Admin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAdminAdapter() {
		if (adminItemProvider == null) {
			adminItemProvider = new AdminItemProvider(this);
		}

		return adminItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.Views} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewsItemProvider viewsItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.Views}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewsAdapter() {
		if (viewsItemProvider == null) {
			viewsItemProvider = new ViewsItemProvider(this);
		}

		return viewsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.ViewInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewInputItemProvider viewInputItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.ViewInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewInputAdapter() {
		if (viewInputItemProvider == null) {
			viewInputItemProvider = new ViewInputItemProvider(this);
		}

		return viewInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.ViewUpdateObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewUpdateObjectItemProvider viewUpdateObjectItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.ViewUpdateObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewUpdateObjectAdapter() {
		if (viewUpdateObjectItemProvider == null) {
			viewUpdateObjectItemProvider = new ViewUpdateObjectItemProvider(this);
		}

		return viewUpdateObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.ViewUpdateAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewUpdateAttributeItemProvider viewUpdateAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.ViewUpdateAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewUpdateAttributeAdapter() {
		if (viewUpdateAttributeItemProvider == null) {
			viewUpdateAttributeItemProvider = new ViewUpdateAttributeItemProvider(this);
		}

		return viewUpdateAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.ViewIndex} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewIndexItemProvider viewIndexItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.ViewIndex}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewIndexAdapter() {
		if (viewIndexItemProvider == null) {
			viewIndexItemProvider = new ViewIndexItemProvider(this);
		}

		return viewIndexItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.ViewAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewAttributeItemProvider viewAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.ViewAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewAttributeAdapter() {
		if (viewAttributeItemProvider == null) {
			viewAttributeItemProvider = new ViewAttributeItemProvider(this);
		}

		return viewAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.ViewAdmin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewAdminItemProvider viewAdminItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.ViewAdmin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewAdminAdapter() {
		if (viewAdminItemProvider == null) {
			viewAdminItemProvider = new ViewAdminItemProvider(this);
		}

		return viewAdminItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.RelationView} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationViewItemProvider relationViewItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.RelationView}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationViewAdapter() {
		if (relationViewItemProvider == null) {
			relationViewItemProvider = new RelationViewItemProvider(this);
		}

		return relationViewItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link Modeluno.modeluno.Page} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PageItemProvider pageItemProvider;

	/**
	 * This creates an adapter for a {@link Modeluno.modeluno.Page}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPageAdapter() {
		if (pageItemProvider == null) {
			pageItemProvider = new PageItemProvider(this);
		}

		return pageItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (mapItemProvider != null) mapItemProvider.dispose();
		if (classItemProvider != null) classItemProvider.dispose();
		if (relationClassItemProvider != null) relationClassItemProvider.dispose();
		if (attributeItemProvider != null) attributeItemProvider.dispose();
		if (relationAttributeItemProvider != null) relationAttributeItemProvider.dispose();
		if (attribute_Not_DerivedItemProvider != null) attribute_Not_DerivedItemProvider.dispose();
		if (attribute_DerivedItemProvider != null) attribute_DerivedItemProvider.dispose();
		if (serviceItemProvider != null) serviceItemProvider.dispose();
		if (relationServiceItemProvider != null) relationServiceItemProvider.dispose();
		if (createItemProvider != null) createItemProvider.dispose();
		if (deleteItemProvider != null) deleteItemProvider.dispose();
		if (updateObjectItemProvider != null) updateObjectItemProvider.dispose();
		if (updateAttributeItemProvider != null) updateAttributeItemProvider.dispose();
		if (listViewItemProvider != null) listViewItemProvider.dispose();
		if (viewItemProvider != null) viewItemProvider.dispose();
		if (adminItemProvider != null) adminItemProvider.dispose();
		if (viewsItemProvider != null) viewsItemProvider.dispose();
		if (viewInputItemProvider != null) viewInputItemProvider.dispose();
		if (viewUpdateObjectItemProvider != null) viewUpdateObjectItemProvider.dispose();
		if (viewUpdateAttributeItemProvider != null) viewUpdateAttributeItemProvider.dispose();
		if (viewIndexItemProvider != null) viewIndexItemProvider.dispose();
		if (viewAttributeItemProvider != null) viewAttributeItemProvider.dispose();
		if (viewAdminItemProvider != null) viewAdminItemProvider.dispose();
		if (relationViewItemProvider != null) relationViewItemProvider.dispose();
		if (pageItemProvider != null) pageItemProvider.dispose();
	}

}
