<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oo_method" nsURI="oo_method" nsPrefix="oo_method">
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rCompound" upperBound="-1"
        eType="#//Relation" containment="true" eOpposite="#//Relation/composed"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rComponents" upperBound="-1"
        eType="#//Relation" eOpposite="#//Relation/component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" lowerBound="1"
        upperBound="-1" eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idFunction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" lowerBound="1"
        upperBound="-1" eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraints" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="composed" lowerBound="1"
        eType="#//Class" eOpposite="#//Class/rCompound"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Class" eOpposite="#//Class/rComponents"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="#//dataTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="permissions" eType="#//permissionsType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="dataTypes">
    <eLiterals name="autonumeric"/>
    <eLiterals name="blob"/>
    <eLiterals name="date"/>
    <eLiterals name="dateTime"/>
    <eLiterals name="int"/>
    <eLiterals name="nat"/>
    <eLiterals name="real"/>
    <eLiterals name="string"/>
    <eLiterals name="text"/>
    <eLiterals name="time"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Derived" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="derFormulas" lowerBound="1"
        upperBound="-1" eType="#//DerivationFormula" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivationComments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotDerived" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivationFormula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" lowerBound="1"
        upperBound="-1" eType="#//Argument" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preconditions" upperBound="-1"
        eType="#//Precondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ServiceKinds"
        defaultValueLiteral="normal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Argument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Precondition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preconditionComments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preFormulas" lowerBound="1"
        upperBound="-1" eType="#//PreconditionFormula" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ServiceKinds">
    <eLiterals name="normal"/>
    <eLiterals name="creation"/>
    <eLiterals name="destruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreconditionFormula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="error" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValuationFormula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraints">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintComments" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constFormulas" lowerBound="1"
        upperBound="-1" eType="#//ConstraintFormula" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintFormula">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="error" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" lowerBound="1"
        upperBound="-1" eType="#//Class" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="permissionsType">
    <eLiterals name="read"/>
    <eLiterals name="write" value="1"/>
    <eLiterals name="both" value="2"/>
  </eClassifiers>
</ecore:EPackage>
