/**
 *
 * $Id$
 */
package Modeldos.modeldos.validation;

import Modeldos.modeldos.Group;
import Modeldos.modeldos.TypeOrientation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Modeldos.modeldos.Menu}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MenuValidator {
	boolean validate();

	boolean validateHasGroup(EList<Group> value);
	boolean validateName(String value);
	boolean validateOrientated(TypeOrientation value);
}
