/**
 *
 * $Id$
 */
package Modeldos.modeldos.validation;

import Modeldos.modeldos.Attributes;
import Modeldos.modeldos.Group;
import Modeldos.modeldos.Menu;
import Modeldos.modeldos.Views;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Modeldos.modeldos.Root}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RootValidator {
	boolean validate();

	boolean validateClass(EList<Modeldos.modeldos.Class> value);
	boolean validateAttribute(EList<Attributes> value);
	boolean validateMenu(EList<Menu> value);
	boolean validateGroup(EList<Group> value);
	boolean validateViews(EList<Views> value);
}
