/**
 *
 * $Id$
 */
package Modeldos.modeldos.validation;

import Modeldos.modeldos.RelationClass;
import Modeldos.modeldos.TypeRol;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Modeldos.modeldos.Views}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ViewsValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateGroupName(String value);
	boolean validateRolView(TypeRol value);
	boolean validateHasRelationClass(EList<RelationClass> value);
	boolean validateViewGoRelationClass(EList<RelationClass> value);
}
