/**
 *
 * $Id$
 */
package Metawebdesign.metawebdesign.validation;

import Metawebdesign.metawebdesign.Derived;
import Metawebdesign.metawebdesign.NotDerived;
import Metawebdesign.metawebdesign.TypeOperator;
import Metawebdesign.metawebdesign.TypeService;

/**
 * A sample validator interface for {@link Metawebdesign.metawebdesign.Constraint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintValidator {
	boolean validate();

	boolean validateAttribute(Derived value);
	boolean validateOperator(TypeOperator value);
	boolean validateService(TypeService value);
	boolean validateName(String value);
	boolean validateValue(NotDerived value);
	boolean validateMansajeError(String value);
}
