/**
 *
 * $Id$
 */
package Metawebdesign.metawebdesign.validation;

import Metawebdesign.metawebdesign.Link;
import Metawebdesign.metawebdesign.typeMenus;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Metawebdesign.metawebdesign.NavegationMenu}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NavegationMenuValidator {
	boolean validate();

	boolean validateHasLink(EList<Link> value);
	boolean validateName(String value);
	boolean validateTypeMenu(typeMenus value);
}
