/**
 *
 * $Id$
 */
package Metawebdesign.metawebdesign.validation;

import Metawebdesign.metawebdesign.Attributes;
import Metawebdesign.metawebdesign.Constraint;
import Metawebdesign.metawebdesign.Group;
import Metawebdesign.metawebdesign.Link;
import Metawebdesign.metawebdesign.Menu;
import Metawebdesign.metawebdesign.ViewComponent;
import Metawebdesign.metawebdesign.Views;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Metawebdesign.metawebdesign.Root}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RootValidator {
	boolean validate();

	boolean validateClass(EList<Metawebdesign.metawebdesign.Class> value);
	boolean validateAttribute(EList<Attributes> value);
	boolean validateMenu(EList<Menu> value);
	boolean validateGroup(EList<Group> value);
	boolean validateViews(EList<Views> value);
	boolean validateView_component(EList<ViewComponent> value);
	boolean validateLink(EList<Link> value);
	boolean validateConstraint(Constraint value);
}
