/**
 *
 * $Id$
 */
package Metawebdesign.metawebdesign.validation;

<<<<<<< HEAD
=======
import Metawebdesign.metawebdesign.RelationView;
>>>>>>> 695e9e7e90f5aebcde04a16e3acfc70b4e09bc98
import Metawebdesign.metawebdesign.TypeRol;
import Metawebdesign.metawebdesign.ViewComponent;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Metawebdesign.metawebdesign.Views}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ViewsValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateRolView(TypeRol value);
<<<<<<< HEAD
=======
	boolean validateHasRelationView(EList<RelationView> value);
	boolean validateFromRelation(EList<RelationView> value);
>>>>>>> 695e9e7e90f5aebcde04a16e3acfc70b4e09bc98
	boolean validateHasViewComponent(EList<ViewComponent> value);
}
