<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metawebdesign" nsURI="http://metawebdesign/1.0" nsPrefix="metawebdesign">
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="class" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//Attributes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//Views" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="view_component" upperBound="-1"
        eType="#//ViewComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1" eType="#//Link"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
        eType="#//Constraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasAttributes" upperBound="15"
        eType="#//Attributes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionCreate" eType="#//TypeRol"
        defaultValueLiteral="authenticated"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionDelete" eType="#//TypeRol"
        defaultValueLiteral="authenticated"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionUpdate" eType="#//TypeRol"
        defaultValueLiteral="authenticated"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionIndex" eType="#//TypeRol"
        defaultValueLiteral="any"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionView" eType="#//TypeRol"
        defaultValueLiteral="any"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionAdmin" eType="#//TypeRol"
        defaultValueLiteral="admin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasRelationClass" upperBound="-1"
        eType="#//RelationClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goRelationClass" upperBound="-1"
        eType="#//RelationClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasView" eType="#//Views"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasRelationConstraint"
        upperBound="-1" eType="#//RelationContraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goRConstriant1" upperBound="-1"
        eType="#//RelationContraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rol" eType="#//TypeRol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="#//TypeData"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inTheForm" eType="#//TypeAttributeForm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeRol">
    <eLiterals name="anonymous"/>
    <eLiterals name="authenticated" value="1"/>
    <eLiterals name="admin" value="2"/>
    <eLiterals name="any" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeAttributeForm">
    <eLiterals name="required"/>
    <eLiterals name="not_required" value="1" literal="not_required"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeData">
    <eLiterals name="numeric"/>
    <eLiterals name="text" value="1"/>
    <eLiterals name="autoincremental" value="2"/>
    <eLiterals name="img" value="3"/>
    <eLiterals name="time" value="6"/>
    <eLiterals name="date" value="7"/>
    <eLiterals name="date_time" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Derived" eSuperTypes="#//Attributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotDerived" eSuperTypes="#//Attributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueDefault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromClass" upperBound="-1"
        eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Attribute_Class_A" eType="#//Attributes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Attribute_Class_B" eType="#//Attributes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cardinality_Class_A" eType="#//typeCardinality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cardinality_Class_B" eType="#//typeCardinality"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="typePresentation">
    <eLiterals name="string"/>
    <eLiterals name="table" value="1"/>
    <eLiterals name="combobox" value="2"/>
    <eLiterals name="radiobuttom" value="3"/>
    <eLiterals name="checkbox" value="4"/>
    <eLiterals name="itemList" value="5"/>
    <eLiterals name="form_email" value="6" literal="form_email"/>
    <eLiterals name="form_password" value="7" literal="form_password"/>
    <eLiterals name="form_file" value="8"/>
    <eLiterals name="form_text" value="9"/>
    <eLiterals name="table_striped" value="10" literal="table_striped"/>
    <eLiterals name="table_bordered" value="11" literal="table_bordered"/>
    <eLiterals name="table_hover" value="12" literal="table_hover"/>
    <eLiterals name="img" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="typeHorizontalPosition">
    <eLiterals name="left"/>
    <eLiterals name="center" value="1"/>
    <eLiterals name="right" value="2" literal="right"/>
    <eLiterals name="EEnumLiteral0" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Views">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rolView" eType="#//TypeRol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasRelationView" upperBound="-1"
        eType="#//RelationView" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRelation" upperBound="-1"
        eType="#//RelationView"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasViewComponent" upperBound="-1"
        eType="#//ViewComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Form" eSuperTypes="#//Views">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" eType="#//TypeService"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeService">
    <eLiterals name="create"/>
    <eLiterals name="update" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" eSuperTypes="#//Views">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Content_HTML" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeOrientation">
    <eLiterals name="topHorizontal"/>
    <eLiterals name="bottomHorizontal" value="1"/>
    <eLiterals name="leftVertical" value="2"/>
    <eLiterals name="rightVertical" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RViewsHasClass" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromClass" upperBound="-1"
        eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ViewAttribute" eSuperTypes="#//ViewComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="getAttribute" eType="#//Attributes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typePresentation" eType="#//typePresentation"
        defaultValueLiteral="string"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionHorizontal" eType="#//typeHorizontalPosition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postionVertical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="From" eType="#//typeViewAttribute"
        defaultValueLiteral="DataBase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NavegationMenu" eSuperTypes="#//ViewComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasLink" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkViewCRUD" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" eType="#//TypeService"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromClass" upperBound="-1"
        eType="#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FromRelation" upperBound="-1"
        eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkView" eSuperTypes="#//Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkView" eType="#//Views"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Attribute" eType="#//Derived"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//TypeOperator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" eType="#//TypeService"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Value" eType="#//NotDerived"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationContraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RhasConstraint" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goRConstraint2" upperBound="-1"
        eType="#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeOperator">
    <eLiterals name="igual"/>
    <eLiterals name="menor" value="1"/>
    <eLiterals name="mayor" value="2"/>
    <eLiterals name="menor_igual" value="3"/>
    <eLiterals name="mayor_igual" value="4"/>
    <eLiterals name="diferente" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="typeViewAttribute">
    <eLiterals name="DataBase"/>
    <eLiterals name="SessionUser"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="typeCardinality">
    <eLiterals name="one"/>
    <eLiterals name="many"/>
  </eClassifiers>
</ecore:EPackage>
